// <auto-generated />
namespace Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class SeriesTags2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeriesTags2));
        
        string IMigrationMetadata.Id
        {
            get { return "201401060113244_Series-Tags-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
