/*

 Copyright (c) 2013-2014 Dmitry Fedorov
 Distributed under the GNU GPL v2. For full terms see the file COPYING.txt

*/

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace Portal.TrackMePro {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PortalConnectorSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entry[]))]
    public partial class PortalConnector : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AvailableGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderPrintFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterAccreditationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccreditationPrintFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback StagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback StageOperationCompleted;
        
        private System.Threading.SendOrPostCallback TargetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllPenalitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllRetiresOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterCallbackOnChangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PortalConnector() {
            this.Url = global::Portal.Properties.Settings.Default.Portal_TrackMePro_PortalConnector;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AvailableGroupsCompletedEventHandler AvailableGroupsCompleted;
        
        /// <remarks/>
        public event RegisterOrderCompletedEventHandler RegisterOrderCompleted;
        
        /// <remarks/>
        public event GetOrderPrintFormCompletedEventHandler GetOrderPrintFormCompleted;
        
        /// <remarks/>
        public event RegisterAccreditationCompletedEventHandler RegisterAccreditationCompleted;
        
        /// <remarks/>
        public event GetAccreditationPrintFormCompletedEventHandler GetAccreditationPrintFormCompleted;
        
        /// <remarks/>
        public event StagesCompletedEventHandler StagesCompleted;
        
        /// <remarks/>
        public event StageCompletedEventHandler StageCompleted;
        
        /// <remarks/>
        public event TargetCompletedEventHandler TargetCompleted;
        
        /// <remarks/>
        public event AllPenalitiesCompletedEventHandler AllPenalitiesCompleted;
        
        /// <remarks/>
        public event AllRetiresCompletedEventHandler AllRetiresCompleted;
        
        /// <remarks/>
        public event AllMessagesCompletedEventHandler AllMessagesCompleted;
        
        /// <remarks/>
        public event RegisterCallbackOnChangeCompletedEventHandler RegisterCallbackOnChangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AvailableGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Group[] AvailableGroups(int eventId) {
            object[] results = this.Invoke("AvailableGroups", new object[] {
                        eventId});
            return ((Group[])(results[0]));
        }
        
        /// <remarks/>
        public void AvailableGroupsAsync(int eventId) {
            this.AvailableGroupsAsync(eventId, null);
        }
        
        /// <remarks/>
        public void AvailableGroupsAsync(int eventId, object userState) {
            if ((this.AvailableGroupsOperationCompleted == null)) {
                this.AvailableGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAvailableGroupsOperationCompleted);
            }
            this.InvokeAsync("AvailableGroups", new object[] {
                        eventId}, this.AvailableGroupsOperationCompleted, userState);
        }
        
        private void OnAvailableGroupsOperationCompleted(object arg) {
            if ((this.AvailableGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AvailableGroupsCompleted(this, new AvailableGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegisterOrder(int eventId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> entryId, Entry entry) {
            object[] results = this.Invoke("RegisterOrder", new object[] {
                        eventId,
                        entryId,
                        entry});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterOrderAsync(int eventId, System.Nullable<int> entryId, Entry entry) {
            this.RegisterOrderAsync(eventId, entryId, entry, null);
        }
        
        /// <remarks/>
        public void RegisterOrderAsync(int eventId, System.Nullable<int> entryId, Entry entry, object userState) {
            if ((this.RegisterOrderOperationCompleted == null)) {
                this.RegisterOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOrderOperationCompleted);
            }
            this.InvokeAsync("RegisterOrder", new object[] {
                        eventId,
                        entryId,
                        entry}, this.RegisterOrderOperationCompleted, userState);
        }
        
        private void OnRegisterOrderOperationCompleted(object arg) {
            if ((this.RegisterOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterOrderCompleted(this, new RegisterOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderPrintForm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetOrderPrintForm(int eventId, int entryId) {
            object[] results = this.Invoke("GetOrderPrintForm", new object[] {
                        eventId,
                        entryId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderPrintFormAsync(int eventId, int entryId) {
            this.GetOrderPrintFormAsync(eventId, entryId, null);
        }
        
        /// <remarks/>
        public void GetOrderPrintFormAsync(int eventId, int entryId, object userState) {
            if ((this.GetOrderPrintFormOperationCompleted == null)) {
                this.GetOrderPrintFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderPrintFormOperationCompleted);
            }
            this.InvokeAsync("GetOrderPrintForm", new object[] {
                        eventId,
                        entryId}, this.GetOrderPrintFormOperationCompleted, userState);
        }
        
        private void OnGetOrderPrintFormOperationCompleted(object arg) {
            if ((this.GetOrderPrintFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderPrintFormCompleted(this, new GetOrderPrintFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterAccreditation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegisterAccreditation(int eventId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> accreditationId, Accreditation accreditation) {
            object[] results = this.Invoke("RegisterAccreditation", new object[] {
                        eventId,
                        accreditationId,
                        accreditation});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAccreditationAsync(int eventId, System.Nullable<int> accreditationId, Accreditation accreditation) {
            this.RegisterAccreditationAsync(eventId, accreditationId, accreditation, null);
        }
        
        /// <remarks/>
        public void RegisterAccreditationAsync(int eventId, System.Nullable<int> accreditationId, Accreditation accreditation, object userState) {
            if ((this.RegisterAccreditationOperationCompleted == null)) {
                this.RegisterAccreditationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterAccreditationOperationCompleted);
            }
            this.InvokeAsync("RegisterAccreditation", new object[] {
                        eventId,
                        accreditationId,
                        accreditation}, this.RegisterAccreditationOperationCompleted, userState);
        }
        
        private void OnRegisterAccreditationOperationCompleted(object arg) {
            if ((this.RegisterAccreditationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterAccreditationCompleted(this, new RegisterAccreditationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccreditationPrintForm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAccreditationPrintForm(int eventId, int accreditationId) {
            object[] results = this.Invoke("GetAccreditationPrintForm", new object[] {
                        eventId,
                        accreditationId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAccreditationPrintFormAsync(int eventId, int accreditationId) {
            this.GetAccreditationPrintFormAsync(eventId, accreditationId, null);
        }
        
        /// <remarks/>
        public void GetAccreditationPrintFormAsync(int eventId, int accreditationId, object userState) {
            if ((this.GetAccreditationPrintFormOperationCompleted == null)) {
                this.GetAccreditationPrintFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccreditationPrintFormOperationCompleted);
            }
            this.InvokeAsync("GetAccreditationPrintForm", new object[] {
                        eventId,
                        accreditationId}, this.GetAccreditationPrintFormOperationCompleted, userState);
        }
        
        private void OnGetAccreditationPrintFormOperationCompleted(object arg) {
            if ((this.GetAccreditationPrintFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccreditationPrintFormCompleted(this, new GetAccreditationPrintFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Stages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMatrixStage[] Stages(int eventId) {
            object[] results = this.Invoke("Stages", new object[] {
                        eventId});
            return ((ResultMatrixStage[])(results[0]));
        }
        
        /// <remarks/>
        public void StagesAsync(int eventId) {
            this.StagesAsync(eventId, null);
        }
        
        /// <remarks/>
        public void StagesAsync(int eventId, object userState) {
            if ((this.StagesOperationCompleted == null)) {
                this.StagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStagesOperationCompleted);
            }
            this.InvokeAsync("Stages", new object[] {
                        eventId}, this.StagesOperationCompleted, userState);
        }
        
        private void OnStagesOperationCompleted(object arg) {
            if ((this.StagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StagesCompleted(this, new StagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Stage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultStageViewModel[] Stage(int eventId, int stageId) {
            object[] results = this.Invoke("Stage", new object[] {
                        eventId,
                        stageId});
            return ((ResultStageViewModel[])(results[0]));
        }
        
        /// <remarks/>
        public void StageAsync(int eventId, int stageId) {
            this.StageAsync(eventId, stageId, null);
        }
        
        /// <remarks/>
        public void StageAsync(int eventId, int stageId, object userState) {
            if ((this.StageOperationCompleted == null)) {
                this.StageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStageOperationCompleted);
            }
            this.InvokeAsync("Stage", new object[] {
                        eventId,
                        stageId}, this.StageOperationCompleted, userState);
        }
        
        private void OnStageOperationCompleted(object arg) {
            if ((this.StageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StageCompleted(this, new StageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Target", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TargetStageViewModel[] Target(int eventId, int stageId) {
            object[] results = this.Invoke("Target", new object[] {
                        eventId,
                        stageId});
            return ((TargetStageViewModel[])(results[0]));
        }
        
        /// <remarks/>
        public void TargetAsync(int eventId, int stageId) {
            this.TargetAsync(eventId, stageId, null);
        }
        
        /// <remarks/>
        public void TargetAsync(int eventId, int stageId, object userState) {
            if ((this.TargetOperationCompleted == null)) {
                this.TargetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTargetOperationCompleted);
            }
            this.InvokeAsync("Target", new object[] {
                        eventId,
                        stageId}, this.TargetOperationCompleted, userState);
        }
        
        private void OnTargetOperationCompleted(object arg) {
            if ((this.TargetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TargetCompleted(this, new TargetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllPenalities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PenalityViewModel[] AllPenalities(int eventId) {
            object[] results = this.Invoke("AllPenalities", new object[] {
                        eventId});
            return ((PenalityViewModel[])(results[0]));
        }
        
        /// <remarks/>
        public void AllPenalitiesAsync(int eventId) {
            this.AllPenalitiesAsync(eventId, null);
        }
        
        /// <remarks/>
        public void AllPenalitiesAsync(int eventId, object userState) {
            if ((this.AllPenalitiesOperationCompleted == null)) {
                this.AllPenalitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllPenalitiesOperationCompleted);
            }
            this.InvokeAsync("AllPenalities", new object[] {
                        eventId}, this.AllPenalitiesOperationCompleted, userState);
        }
        
        private void OnAllPenalitiesOperationCompleted(object arg) {
            if ((this.AllPenalitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllPenalitiesCompleted(this, new AllPenalitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllRetires", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetireViewModel[] AllRetires(int eventId) {
            object[] results = this.Invoke("AllRetires", new object[] {
                        eventId});
            return ((RetireViewModel[])(results[0]));
        }
        
        /// <remarks/>
        public void AllRetiresAsync(int eventId) {
            this.AllRetiresAsync(eventId, null);
        }
        
        /// <remarks/>
        public void AllRetiresAsync(int eventId, object userState) {
            if ((this.AllRetiresOperationCompleted == null)) {
                this.AllRetiresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllRetiresOperationCompleted);
            }
            this.InvokeAsync("AllRetires", new object[] {
                        eventId}, this.AllRetiresOperationCompleted, userState);
        }
        
        private void OnAllRetiresOperationCompleted(object arg) {
            if ((this.AllRetiresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllRetiresCompleted(this, new AllRetiresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageViewModel[] AllMessages(int eventId) {
            object[] results = this.Invoke("AllMessages", new object[] {
                        eventId});
            return ((MessageViewModel[])(results[0]));
        }
        
        /// <remarks/>
        public void AllMessagesAsync(int eventId) {
            this.AllMessagesAsync(eventId, null);
        }
        
        /// <remarks/>
        public void AllMessagesAsync(int eventId, object userState) {
            if ((this.AllMessagesOperationCompleted == null)) {
                this.AllMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllMessagesOperationCompleted);
            }
            this.InvokeAsync("AllMessages", new object[] {
                        eventId}, this.AllMessagesOperationCompleted, userState);
        }
        
        private void OnAllMessagesOperationCompleted(object arg) {
            if ((this.AllMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllMessagesCompleted(this, new AllMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterCallbackOnChange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegisterCallbackOnChange(int eventId, string url) {
            this.Invoke("RegisterCallbackOnChange", new object[] {
                        eventId,
                        url});
        }
        
        /// <remarks/>
        public void RegisterCallbackOnChangeAsync(int eventId, string url) {
            this.RegisterCallbackOnChangeAsync(eventId, url, null);
        }
        
        /// <remarks/>
        public void RegisterCallbackOnChangeAsync(int eventId, string url, object userState) {
            if ((this.RegisterCallbackOnChangeOperationCompleted == null)) {
                this.RegisterCallbackOnChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterCallbackOnChangeOperationCompleted);
            }
            this.InvokeAsync("RegisterCallbackOnChange", new object[] {
                        eventId,
                        url}, this.RegisterCallbackOnChangeOperationCompleted, userState);
        }
        
        private void OnRegisterCallbackOnChangeOperationCompleted(object arg) {
            if ((this.RegisterCallbackOnChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCallbackOnChangeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Group {
        
        private int idField;
        
        private string nameField;
        
        private int sortOrderField;
        
        private bool isCountableField;
        
        private float entryFeeField;
        
        private string entryFormViewField;
        
        private Entry[] entriesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCountable {
            get {
                return this.isCountableField;
            }
            set {
                this.isCountableField = value;
            }
        }
        
        /// <remarks/>
        public float EntryFee {
            get {
                return this.entryFeeField;
            }
            set {
                this.entryFeeField = value;
            }
        }
        
        /// <remarks/>
        public string EntryFormView {
            get {
                return this.entryFormViewField;
            }
            set {
                this.entryFormViewField = value;
            }
        }
        
        /// <remarks/>
        public Entry[] Entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Entry {
        
        private int idField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string licenseField;
        
        private System.Nullable<System.DateTime> birthDayField;
        
        private string cityField;
        
        private System.Nullable<int> locationField;
        
        private string emailField;
        
        private string phoneField;
        
        private string addressField;
        
        private string iNNField;
        
        private string passportField;
        
        private string coDriverFirstNameField;
        
        private string coDriverLastNameField;
        
        private string coDriverLicenseField;
        
        private string coDriverCityField;
        
        private System.Nullable<System.DateTime> coDriverBirthDateField;
        
        private string coDriverEmailField;
        
        private string coDriverPhoneField;
        
        private string coDriverPassportField;
        
        private object coDriverAddressField;
        
        private string teamPhoneField;
        
        private string teamField;
        
        private string teamLicenseField;
        
        private string teamFaxField;
        
        private string teamEmailField;
        
        private string teamCityField;
        
        private string teamAddressField;
        
        private Group[] groupsField;
        
        private System.Nullable<System.DateTime> ensuranceTillField;
        
        private System.Nullable<System.DateTime> medicalCheckTillField;
        
        private System.Nullable<System.DateTime> parentPermissionField;
        
        private float entryFeeToPayField;
        
        private System.Nullable<float> entryFeeToPaidField;
        
        private string markField;
        
        private string modelField;
        
        private string registrationNumberField;
        
        private string engineField;
        
        private string carYearField;
        
        private System.Nullable<int> startNumberField;
        
        private EntryState stateField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string License {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BirthDay {
            get {
                return this.birthDayField;
            }
            set {
                this.birthDayField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <remarks/>
        public string Passport {
            get {
                return this.passportField;
            }
            set {
                this.passportField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverFirstName {
            get {
                return this.coDriverFirstNameField;
            }
            set {
                this.coDriverFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverLastName {
            get {
                return this.coDriverLastNameField;
            }
            set {
                this.coDriverLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverLicense {
            get {
                return this.coDriverLicenseField;
            }
            set {
                this.coDriverLicenseField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverCity {
            get {
                return this.coDriverCityField;
            }
            set {
                this.coDriverCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CoDriverBirthDate {
            get {
                return this.coDriverBirthDateField;
            }
            set {
                this.coDriverBirthDateField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverEmail {
            get {
                return this.coDriverEmailField;
            }
            set {
                this.coDriverEmailField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverPhone {
            get {
                return this.coDriverPhoneField;
            }
            set {
                this.coDriverPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriverPassport {
            get {
                return this.coDriverPassportField;
            }
            set {
                this.coDriverPassportField = value;
            }
        }
        
        /// <remarks/>
        public object CoDriverAddress {
            get {
                return this.coDriverAddressField;
            }
            set {
                this.coDriverAddressField = value;
            }
        }
        
        /// <remarks/>
        public string TeamPhone {
            get {
                return this.teamPhoneField;
            }
            set {
                this.teamPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
            }
        }
        
        /// <remarks/>
        public string TeamLicense {
            get {
                return this.teamLicenseField;
            }
            set {
                this.teamLicenseField = value;
            }
        }
        
        /// <remarks/>
        public string TeamFax {
            get {
                return this.teamFaxField;
            }
            set {
                this.teamFaxField = value;
            }
        }
        
        /// <remarks/>
        public string TeamEmail {
            get {
                return this.teamEmailField;
            }
            set {
                this.teamEmailField = value;
            }
        }
        
        /// <remarks/>
        public string TeamCity {
            get {
                return this.teamCityField;
            }
            set {
                this.teamCityField = value;
            }
        }
        
        /// <remarks/>
        public string TeamAddress {
            get {
                return this.teamAddressField;
            }
            set {
                this.teamAddressField = value;
            }
        }
        
        /// <remarks/>
        public Group[] Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EnsuranceTill {
            get {
                return this.ensuranceTillField;
            }
            set {
                this.ensuranceTillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> MedicalCheckTill {
            get {
                return this.medicalCheckTillField;
            }
            set {
                this.medicalCheckTillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ParentPermission {
            get {
                return this.parentPermissionField;
            }
            set {
                this.parentPermissionField = value;
            }
        }
        
        /// <remarks/>
        public float EntryFeeToPay {
            get {
                return this.entryFeeToPayField;
            }
            set {
                this.entryFeeToPayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> EntryFeeToPaid {
            get {
                return this.entryFeeToPaidField;
            }
            set {
                this.entryFeeToPaidField = value;
            }
        }
        
        /// <remarks/>
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Engine {
            get {
                return this.engineField;
            }
            set {
                this.engineField = value;
            }
        }
        
        /// <remarks/>
        public string CarYear {
            get {
                return this.carYearField;
            }
            set {
                this.carYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> StartNumber {
            get {
                return this.startNumberField;
            }
            set {
                this.startNumberField = value;
            }
        }
        
        /// <remarks/>
        public EntryState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageViewModel {
        
        private string titleField;
        
        private System.DateTime timeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetireViewModel {
        
        private int startNumberField;
        
        private string driverField;
        
        private string coDriverField;
        
        private string groupsField;
        
        private string controlPointNameField;
        
        private string reasonField;
        
        private int controlPointOrderField;
        
        /// <remarks/>
        public int StartNumber {
            get {
                return this.startNumberField;
            }
            set {
                this.startNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriver {
            get {
                return this.coDriverField;
            }
            set {
                this.coDriverField = value;
            }
        }
        
        /// <remarks/>
        public string Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public string ControlPointName {
            get {
                return this.controlPointNameField;
            }
            set {
                this.controlPointNameField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public int ControlPointOrder {
            get {
                return this.controlPointOrderField;
            }
            set {
                this.controlPointOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PenalityViewModel {
        
        private int startNumberField;
        
        private string driverField;
        
        private string coDriverField;
        
        private string groupsField;
        
        private string controlPointNameField;
        
        private string reasonField;
        
        private decimal valueSecondsField;
        
        private int controlPointOrderField;
        
        /// <remarks/>
        public int StartNumber {
            get {
                return this.startNumberField;
            }
            set {
                this.startNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriver {
            get {
                return this.coDriverField;
            }
            set {
                this.coDriverField = value;
            }
        }
        
        /// <remarks/>
        public string Groups {
            get {
                return this.groupsField;
            }
            set {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        public string ControlPointName {
            get {
                return this.controlPointNameField;
            }
            set {
                this.controlPointNameField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValueSeconds {
            get {
                return this.valueSecondsField;
            }
            set {
                this.valueSecondsField = value;
            }
        }
        
        /// <remarks/>
        public int ControlPointOrder {
            get {
                return this.controlPointOrderField;
            }
            set {
                this.controlPointOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TargetStageViewModel {
        
        private System.Nullable<int> startNumberField;
        
        private string driverField;
        
        private string coDriverField;
        
        private string groupField;
        
        private decimal resultField;
        
        private System.Nullable<System.DateTime> startTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> StartNumber {
            get {
                return this.startNumberField;
            }
            set {
                this.startNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriver {
            get {
                return this.coDriverField;
            }
            set {
                this.coDriverField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PenalityDetail {
        
        private string controlPointField;
        
        private string reasonField;
        
        private decimal valueField;
        
        /// <remarks/>
        public string ControlPoint {
            get {
                return this.controlPointField;
            }
            set {
                this.controlPointField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultStageViewModel {
        
        private bool isSecondsResultField;
        
        private System.Nullable<int> startNumberField;
        
        private string driverField;
        
        private string coDriverField;
        
        private string groupField;
        
        private decimal resultBeforeField;
        
        private int positionBeforeField;
        
        private decimal resultField;
        
        private decimal penalityField;
        
        private decimal resultRawField;
        
        private decimal resultAfterField;
        
        private decimal positionAfterField;
        
        private PenalityDetail[] penalityDetailsField;
        
        private bool hasResultField;
        
        private string retireReasonField;
        
        /// <remarks/>
        public bool IsSecondsResult {
            get {
                return this.isSecondsResultField;
            }
            set {
                this.isSecondsResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> StartNumber {
            get {
                return this.startNumberField;
            }
            set {
                this.startNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Driver {
            get {
                return this.driverField;
            }
            set {
                this.driverField = value;
            }
        }
        
        /// <remarks/>
        public string CoDriver {
            get {
                return this.coDriverField;
            }
            set {
                this.coDriverField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public decimal ResultBefore {
            get {
                return this.resultBeforeField;
            }
            set {
                this.resultBeforeField = value;
            }
        }
        
        /// <remarks/>
        public int PositionBefore {
            get {
                return this.positionBeforeField;
            }
            set {
                this.positionBeforeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public decimal Penality {
            get {
                return this.penalityField;
            }
            set {
                this.penalityField = value;
            }
        }
        
        /// <remarks/>
        public decimal ResultRaw {
            get {
                return this.resultRawField;
            }
            set {
                this.resultRawField = value;
            }
        }
        
        /// <remarks/>
        public decimal ResultAfter {
            get {
                return this.resultAfterField;
            }
            set {
                this.resultAfterField = value;
            }
        }
        
        /// <remarks/>
        public decimal PositionAfter {
            get {
                return this.positionAfterField;
            }
            set {
                this.positionAfterField = value;
            }
        }
        
        /// <remarks/>
        public PenalityDetail[] PenalityDetails {
            get {
                return this.penalityDetailsField;
            }
            set {
                this.penalityDetailsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasResult {
            get {
                return this.hasResultField;
            }
            set {
                this.hasResultField = value;
            }
        }
        
        /// <remarks/>
        public string RetireReason {
            get {
                return this.retireReasonField;
            }
            set {
                this.retireReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultMatrixStage {
        
        private int idField;
        
        private string nameField;
        
        private bool overdueField;
        
        private string detailsActionField;
        
        private string descriptionField;
        
        private bool isTargetField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool Overdue {
            get {
                return this.overdueField;
            }
            set {
                this.overdueField = value;
            }
        }
        
        /// <remarks/>
        public string DetailsAction {
            get {
                return this.detailsActionField;
            }
            set {
                this.detailsActionField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTarget {
            get {
                return this.isTargetField;
            }
            set {
                this.isTargetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MediaInfoEntry {
        
        private int idField;
        
        private string mediaField;
        
        private string positionField;
        
        private string organisationField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string webField;
        
        private MediaType typeField;
        
        private string regionField;
        
        private string frequencyField;
        
        private string editionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string Organisation {
            get {
                return this.organisationField;
            }
            set {
                this.organisationField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        public MediaType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public string Edition {
            get {
                return this.editionField;
            }
            set {
                this.editionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MediaType {
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        Photo,
        
        /// <remarks/>
        Team,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Accreditation {
        
        private int idField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string locationField;
        
        private string phoneField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private string passportField;
        
        private string addressField;
        
        private string carField;
        
        private MediaInfoEntry[] mediaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Passport {
            get {
                return this.passportField;
            }
            set {
                this.passportField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Car {
            get {
                return this.carField;
            }
            set {
                this.carField = value;
            }
        }
        
        /// <remarks/>
        public MediaInfoEntry[] Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EntryState {
        
        /// <remarks/>
        Redimmed,
        
        /// <remarks/>
        Preliminary,
        
        /// <remarks/>
        AdministrativePassed,
        
        /// <remarks/>
        TechChecksComplete,
        
        /// <remarks/>
        Retired,
        
        /// <remarks/>
        Excluded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AvailableGroupsCompletedEventHandler(object sender, AvailableGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvailableGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AvailableGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Group[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Group[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RegisterOrderCompletedEventHandler(object sender, RegisterOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetOrderPrintFormCompletedEventHandler(object sender, GetOrderPrintFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderPrintFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderPrintFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RegisterAccreditationCompletedEventHandler(object sender, RegisterAccreditationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterAccreditationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterAccreditationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAccreditationPrintFormCompletedEventHandler(object sender, GetAccreditationPrintFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccreditationPrintFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccreditationPrintFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void StagesCompletedEventHandler(object sender, StagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMatrixStage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMatrixStage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void StageCompletedEventHandler(object sender, StageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultStageViewModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultStageViewModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TargetCompletedEventHandler(object sender, TargetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TargetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TargetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TargetStageViewModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TargetStageViewModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AllPenalitiesCompletedEventHandler(object sender, AllPenalitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllPenalitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllPenalitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PenalityViewModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PenalityViewModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AllRetiresCompletedEventHandler(object sender, AllRetiresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllRetiresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllRetiresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetireViewModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetireViewModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AllMessagesCompletedEventHandler(object sender, AllMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageViewModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageViewModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RegisterCallbackOnChangeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591